/**
* Created by bavv on 26/06/2020
* Copyright (c) 2020 bavv
*/

export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_FIRST_INSTALL = "SET_FIRST_INSTALL";

export const UPDATE_CODEPUSH_DATA = "UPDATE_CODEPUSH_DATA";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGIN_SOCIAL = "LOGIN_SOCIAL";
export const LOGIN_SOCIAL_SUCCESS = "LOGIN_SOCIAL_SUCCESS";
export const LOGIN_SOCIAL_FAILED = "LOGIN_SOCIAL_FAILED";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

export const RESET_CONFIG = "RESET_CONFIG";
export const LOGOUT = "LOGOUT";

export const CONFIG_INITED = "CONFIG_INITED";

export const UPDATE_WISHLIST = "UPDATE_WISHLIST";

export const GET_STORE_BY_ID = "GET_STORE_BY_ID";
export const GET_STORE_BY_ID_SUCCESS = "GET_STORE_BY_ID_SUCCESS";
export const GET_STORE_BY_ID_FAILED = "GET_STORE_BY_ID_FAILED";

export const GET_HOME_PRODUCT = "GET_HOME_PRODUCT";
export const GET_HOME_PRODUCT_SUCCESS = "GET_HOME_PRODUCT_SUCCESS";
export const GET_HOME_PRODUCT_FAILED = "GET_HOME_PRODUCT_FAILED";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";

export const GET_PRODUCT_BY_CATE_ID = "GET_PRODUCT_BY_CATE_ID";
export const GET_PRODUCT_BY_CATE_ID_SUCCESS = "GET_PRODUCT_BY_CATE_ID_SUCCESS";
export const GET_PRODUCT_BY_CATE_ID_FAILED = "GET_PRODUCT_BY_CATE_ID_FAILED";

export const GET_PRODUCT_RELATE = "GET_PRODUCT_RELATE";
export const GET_PRODUCT_RELATE_SUCCESS = "GET_PRODUCT_RELATE_SUCCESS";
export const GET_PRODUCT_RELATE_FAILED = "GET_PRODUCT_RELATE_FAILED";

export const GET_PRODUCT_BY_CATE_CHILD_ID = "GET_PRODUCT_BY_CATE_CHILD_ID";
export const GET_PRODUCT_BY_CATE_CHILD_ID_SUCCESS = "GET_PRODUCT_BY_CATE_CHILD_ID_SUCCESS";
export const GET_PRODUCT_BY_CATE_CHILD_ID_FAILED = "GET_PRODUCT_BY_CATE_CHILD_ID_FAILED";

export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_DETAIL_FAILED = "GET_PRODUCT_DETAIL_FAILED";

export const SELECT_VARIANT = "SELECT_VARIANT";
export const REMOVE_VARIANT = "REMOVE_VARIANT";
export const RESET_VARIANT = "RESET_VARIANT";

export const RESET_HOME_SCREEN = "RESET_HOME_SCREEN";
export const RESET_PRODUCT_SCREEN = "RESET_PRODUCT_SCREEN";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";

export const GET_CHILD_CATEGORY = "GET_CHILD_CATEGORY";
export const GET_CHILD_CATEGORY_SUCCESS = "GET_CHILD_CATEGORY_SUCCESS";
export const GET_CHILD_CATEGORY_FAILED = "GET_CHILD_CATEGORY_FAILED";

export const SET_CHILD_CATEGORY = "SET_CHILD_CATEGORY";
export const SET_CHILD_CATEGORY_SUCCESS = "SET_CHILD_CATEGORY_SUCCESS";

export const GET_MY_CART = "GET_MY_CART";
export const GET_MY_CART_SUCCESS = "GET_MY_CART_SUCCESS";
export const GET_MY_CART_FAILED = "GET_MY_CART_FAILED";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";

export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const REMOVE_ITEM_FROM_CART_SUCCESS = "REMOVE_ITEM_FROM_CART_SUCCESS";
export const REMOVE_ITEM_FROM_CART_FAILED = "REMOVE_ITEM_FROM_CART_FAILED";

export const CLEAR_DISABLED_ITEM_FROM_CART = "CLEAR_DISABLED_ITEM_FROM_CART";
export const CLEAR_DISABLED_ITEM_FROM_CART_SUCCESS = "CLEAR_DISABLED_ITEM_FROM_CART_SUCCESS";
export const CLEAR_DISABLED_ITEM_FROM_CART_FAILED = "CLEAR_DISABLED_ITEM_FROM_CART_FAILED";

export const CHANGE_QUANTITY_ITEM_IN_CART = "CHANGE_QUANTITY_ITEM_IN_CART";
export const CHANGE_QUANTITY_ITEM_IN_CART_SUCCESS = "CHANGE_QUANTITY_ITEM_IN_CART_SUCCESS";
export const CHANGE_QUANTITY_ITEM_IN_CART_FAILED = "CHANGE_QUANTITY_ITEM_IN_CART_FAILED";

export const DRAFT_CART = "DRAFT_CART";
export const DRAFT_CART_SUCCESS = "DRAFT_CART_SUCCESS";
export const DRAFT_CART_FAILED = "DRAFT_CART_FAILED";

export const GET_ORDER = "GET_ORDER";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED = "GET_ORDER_FAILED";

export const GET_ORDER_OF_STORE = "GET_ORDER_OF_STORE";
export const GET_ORDER_OF_STORE_SUCCESS = "GET_ORDER_OF_STORE_SUCCESS";
export const GET_ORDER_OF_STORE_FAILED = "GET_ORDER_OF_STORE_FAILED";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";

export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL";
export const GET_ORDER_DETAIL_SUCCESS = "GET_ORDER_DETAIL_SUCCESS";
export const GET_ORDER_DETAIL_FAILED = "GET_ORDER_DETAIL_FAILED";

export const CANCEL_ORDER = "CANCEL_ORDER";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAILED = "CANCEL_ORDER_FAILED";

export const CANCEL_ITEM_IN_ORDER = "CANCEL_ITEM_IN_ORDER";
export const CANCEL_ITEM_IN_ORDER_SUCCESS = "CANCEL_ITEM_IN_ORDER_SUCCESS";
export const CANCEL_ITEM_IN_ORDER_FAILED = "CANCEL_ITEM_IN_ORDER_FAILED";

export const GET_CITY = "GET_CITY";
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_FAILED = "GET_CITY_FAILED";

export const GET_DISTRICT = "GET_DISTRICT";
export const GET_DISTRICT_SUCCESS = "GET_DISTRICT_SUCCESS";
export const GET_DISTRICT_FAILED = "GET_DISTRICT_FAILED";

export const GET_WARD = "GET_WARD";
export const GET_WARD_SUCCESS = "GET_WARD_SUCCESS";
export const GET_WARD_FAILED = "GET_WARD_FAILED";

export const GET_MY_SHIPPING_ADDRESS = "GET_MY_SHIPPING_ADDRESS";
export const GET_MY_SHIPPING_ADDRESS_SUCCESS = "GET_MY_SHIPPING_ADDRESS_SUCCESS";
export const GET_MY_SHIPPING_ADDRESS_FAILED = "GET_MY_SHIPPING_ADDRESS_FAILED";

export const ADD_MY_SHIPPING_ADDRESS = "ADD_MY_SHIPPING_ADDRESS";
export const ADD_MY_SHIPPING_ADDRESS_SUCCESS = "ADD_MY_SHIPPING_ADDRESS_SUCCESS";
export const ADD_MY_SHIPPING_ADDRESS_FAILED = "ADD_MY_SHIPPING_ADDRESS_FAILED";

// Notification
export const ADD_USER_ID_DEVICE = "ADD_USER_ID_DEVICE";
export const ADD_USER_ID_DEVICE_SUCCESS = "ADD_USER_ID_DEVICE_SUCCESS";
export const ADD_USER_ID_DEVICE_FAILED = "ADD_USER_ID_DEVICE_FAILED";

export const REMOVE_USER_ID_DEVICE = "REMOVE_USER_ID_DEVICE";
export const REMOVE_USER_ID_DEVICE_SUCCESS = "REMOVE_USER_ID_DEVICE_SUCCESS";
export const REMOVE_USER_ID_DEVICE_FAILED = "REMOVE_USER_ID_DEVICE_FAILED";

export const GET_MY_WISHLIST = "GET_MY_WISHLIST";
export const GET_MY_WISHLIST_SUCCESS = "GET_MY_WISHLIST_SUCCESS";
export const GET_MY_WISHLIST_FAILED = "GET_MY_WISHLIST_FAILED";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_FAILED = "ADD_TO_WISHLIST_FAILED";

export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const REMOVE_FROM_WISHLIST_SUCCESS = "REMOVE_FROM_WISHLIST_SUCCESS";
export const REMOVE_FROM_WISHLIST_FAILED = "REMOVE_FROM_WISHLIST_FAILED";

export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAILED = "GET_NOTIFICATION_FAILED";

export const GET_LIVESTREAM = "GET_LIVESTREAM";
export const GET_LIVESTREAM_SUCCESS = "GET_LIVESTREAM_SUCCESS";
export const GET_LIVESTREAM_FAILED = "GET_LIVESTREAM_FAILED";

export const GET_LIVESTREAM_DETAIL = "GET_LIVESTREAM_DETAIL";
export const GET_LIVESTREAM_DETAIL_SUCCESS = "GET_LIVESTREAM_DETAIL_SUCCESS";
export const GET_LIVESTREAM_DETAIL_FAILED = "GET_LIVESTREAM_DETAIL_FAILED";

export const GET_PRODUCT_OF_LIVESTREAM = "GET_PRODUCT_OF_LIVESTREAM";
export const GET_PRODUCT_OF_LIVESTREAM_SUCCESS = "GET_PRODUCT_OF_LIVESTREAM_SUCCESS";
export const GET_PRODUCT_OF_LIVESTREAM_FAILED = "GET_PRODUCT_OF_LIVESTREAM_FAILED";

// banner
export const GET_BANNER = "GET_BANNER";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAILED = "GET_BANNER_FAILED";
// flag
export const GET_FLAG = "GET_FLAG";
export const GET_FLAG_SUCCESS = "GET_FLAG_SUCCESS";
export const GET_FLAG_FAILED = "GET_BANNGET_FLAG_FAILEDER_FAILED";